'use client';

import { useEffect, useMemo, useState } from 'react';

const DAYS = [
  ['Rennes','Sep 12','Gateway',0,'Rennes',['Parlement de Bretagne','Place des Lices','Les Halles Centrales'],'Easy arrival day; keep the evening flexible.','18° · Partly cloudy'],
  ['Mont-Saint-Michel','Sep 13','Bay',78,'Saint-Malo',['Abbey','Grande Rue','Bay viewpoint'],'Arrive early to beat the midday crowds.','17° · Clear'],
  ['Saint-Malo','Sep 14','Emerald Coast',55,'Saint-Malo',['Ramparts','Plage du Sillon','Fort National'],'Build the day around tide conditions.','18° · Coastal breeze'],
  ['Dinan → Cap Fréhel','Sep 15','North Coast',125,'Paimpol',['Dinan old town','Fort La Latte','Cap Fréhel'],'Scenic driving day; leave buffer for viewpoints.','17° · Windy'],
  ['Pink Granite Coast','Sep 16','Côte de Granit Rose',105,'Morlaix',["Ploumanac'h",'Trégastel','Morlaix'],'High-value scenery day; protect sunset time.','18° · Clear'],
  ['Brest → Crozon','Sep 17','Finistère',125,'Crozon',['Brest waterfront','Pointe de Pen-Hir','Crozon Peninsula'],'Wild Atlantic landscapes; keep a wind backup.','16° · Atlantic wind'],
  ['Pointe du Raz → Quimper','Sep 18','West Brittany',115,'Quimper',['Pointe du Raz','Baie des Trépassés','Quimper old town'],'Keep the afternoon for Quimper.','17° · Cloud breaks'],
  ['Concarneau → Carnac','Sep 19','South Coast',135,'Quiberon',['Ville Close','Carnac alignments','Quiberon coast'],'History + ocean in one day.','19° · Mild'],
  ['Belle-Île / Gulf of Morbihan','Sep 20','Morbihan',0,'Vannes',['Belle-Île','Port of Vannes','Old town'],'Weather-sensitive island day; preserve a mainland backup.','19° · Ferry weather'],
  ['Vannes','Sep 21','Finish',0,'—',['Remparts','Harbor','Departure'],'No hard scheduling after noon.','19° · Mild']
].map((d,i)=>({day:i+1,city:d[0],date:d[1],region:d[2],km:d[3],stay:d[4],items:d[5],note:d[6],weather:d[7]}));

const BASE_BUDGET={lodging:1350,food:620,fuel:210,activities:320,ferries:120,buffer:250};
const DEFAULT_PACKING=['Passport / ID','Driving documents','Phone + charger','Power bank','Rain shell','Walking shoes','Swimwear','Small daypack','Sunglasses','Essentials'];

export default function Home(){
 const [day,setDay]=useState(3),[view,setView]=useState('command'),[saved,setSaved]=useState(false),[notes,setNotes]=useState('Book the island/ferry day only after checking weather and sailing availability.'),[budget,setBudget]=useState(BASE_BUDGET),[packed,setPacked]=useState([]),[packing,setPacking]=useState(DEFAULT_PACKING),[checks,setChecks]=useState({}),[toast,setToast]=useState('');
 const trip=DAYS[day-1], km=useMemo(()=>DAYS.reduce((a,d)=>a+d.km,0),[]), total=Object.values(budget).reduce((a,b)=>a+Number(b||0),0), health=Math.max(88,100-(packed.length<5?4:0)-(notes?0:5));
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('brittany-trip')||'{}');if(x.notes)setNotes(x.notes);if(x.budget)setBudget(x.budget);if(x.packed)setPacked(x.packed);if(x.packing)setPacking(x.packing);if(x.checks)setChecks(x.checks);if(x.saved)setSaved(x.saved)}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem('brittany-trip',JSON.stringify({notes,budget,packed,packing,checks,saved}))}catch{}},[notes,budget,packed,packing,checks,saved]);
 const notify=x=>{setToast(x);setTimeout(()=>setToast(''),1800)};
 const exportTrip=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({trip:'Brittany',route:DAYS,budget,notes,packing},null,2)],{type:'application/json'}));a.download='brittany-itinerary.json';a.click();notify('Trip exported');};
 return <main>
  <header className="topbar"><div className="brand"><div className="brandMark">B</div><div><b>BRITTANY</b><span>TRIP COMMAND CENTER</span></div></div><nav>{[['command','Command'],['timeline','Timeline'],['map','Route'],['plan','Plan'],['budget','Budget']].map(([v,l])=><button key={v} className={view===v?'nav active':'nav'} onClick={()=>setView(v)}>{l}</button>)}</nav><div className="actions"><button className="ghost" onClick={()=>{setSaved(!saved);notify(saved?'Save removed':'Saved locally')}}>{saved?'★ Saved':'☆ Save'}</button><button className="primary" onClick={exportTrip}>Export</button></div></header>
  <section className="hero"><div className="heroCopy"><div className="eyebrow">FRANCE · 10 DAYS · ROAD TRIP</div><h1>Brittany,<br/><em>beautifully planned.</em></h1><p>A living command center for route sequencing, stays, coastal timing, packing, budget and weather-sensitive decisions.</p><div className="heroMeta"><span>● 10 days</span><span>⌁ ~{km} km</span><span>◒ 9 bases</span><span>✦ {health}/100 health</span></div></div><div className="heroOrb"><div className="orbLabel">ATLANTIC<br/><strong>01—10</strong></div><div className="orbRoute"><i/><i/><i/><i/><i/></div></div></section>
  <div className="shell"><div className="sectionHead"><div><div className="eyebrow">LIVE TRIP BOARD</div><h2>{view==='command'?'Your trip at a glance':view==='timeline'?'Day-by-day timeline':view==='map'?'Route intelligence':view==='plan'?'Trip planner':'Trip budget'}</h2></div><div className="progress"><span>DAY {day} / 10</span><div><i style={{width:`${day*10}%`}}/></div><b>{day*10}%</b></div></div>
   {view==='command'&&<div className="dashboard"><aside className="dayRail">{DAYS.map(d=><button key={d.day} className={day===d.day?'day active':'day'} onClick={()=>setDay(d.day)}><span>{String(d.day).padStart(2,'0')}</span><div><b>{d.city}</b><small>{d.date} · {d.stay}</small></div><strong>✦</strong></button>)}</aside><section className="mainPanel"><RouteMap day={day} setDay={setDay}/><div className="cards"><article className="card large"><div className="cardTop"><span>DAY {trip.day}</span><span>{trip.date}</span></div><h3>{trip.city}</h3><p>{trip.note}</p><div className="stops">{trip.items.map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div><div className="smartRow"><span>☁ {trip.weather}</span><span>◒ Tide-aware</span><span>⌁ Scenic priority</span></div></article><article className="card"><span className="eyebrow">LOGISTICS</span><h3>{trip.km?`${trip.km} km`:'Local'}</h3><p>Estimated route distance</p><hr/><b>Overnight</b><strong>{trip.stay}</strong><button className="cardButton" onClick={()=>setView('plan')}>Open stay plan →</button></article><article className="card"><span className="eyebrow">TRIP HEALTH</span><div className="health"><strong>{health}</strong><span>/100</span></div><p>Strong pacing. Day 9 is the main weather/ferry dependency.</p><div className="healthbar"><i style={{width:`${health}%`}}/></div><button className="cardButton" onClick={()=>setView('plan')}>Run audit →</button></article></div></section></div>}
   {view==='timeline'&&<div className="timeline">{DAYS.map(d=><button key={d.day} className={day===d.day?'timelineRow selected':'timelineRow'} onClick={()=>setDay(d.day)}><div className="time">{d.date}<b>DAY {d.day}</b></div><div className="line"><i/></div><div className="tlBody"><h3>{d.city}</h3><span>{d.region} · {d.km?`${d.km} km`:'local'}</span><p>{d.items.join(' · ')}</p></div></button>)}</div>}
   {view==='map'&&<RouteMap day={day} setDay={setDay} full/>}
   {view==='plan'&&<div className="plannerGrid"><section className="card plannerMain"><div className="plannerHeader"><div><span className="eyebrow">DAY PLANNER</span><h3>{trip.date} · {trip.city}</h3></div><button onClick={()=>setDay(day===10?1:day+1)}>Next day →</button></div><div className="planItems">{trip.items.map((x,i)=>{const k=`${day}-${i}`;return <label className="planItem" key={x}><input type="checkbox" checked={!!checks[k]} onChange={e=>setChecks({...checks,[k]:e.target.checked})}/><span><b>0{i+1}</b>{x}</span><small>{i===0?'Morning':i===1?'Midday':'Flexible'}</small></label>})}</div><div className="noteBox"><span className="eyebrow">TRIP NOTE</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></div></section><aside className="sideStack"><div className="card"><span className="eyebrow">CONDITIONS</span><div className="metric"><b>{trip.weather.split(' · ')[0]}</b><span>{trip.weather.split(' · ')[1]}</span></div><p>Forecast and official tide connectors are API-ready; verify live conditions before coastal or ferry activities.</p><button className="cardButton" onClick={()=>notify('Live weather connector ready for API key')}>Connect live weather →</button></div><div className="card"><span className="eyebrow">PACKING</span><h3>{packed.length}/{packing.length}</h3><div className="packingBar"><i style={{width:`${packed.length/packing.length*100}%`}}/></div><button className="cardButton" onClick={()=>setView('budget')}>Open checklist →</button></div></aside></div>}
   {view==='budget'&&<div className="budgetGrid"><section className="card budgetMain"><span className="eyebrow">TRIP COST MODEL</span><div className="budgetTotal">€{total.toLocaleString()}<small> planned envelope</small></div>{Object.entries(budget).map(([k,v])=><label className="budgetLine" key={k}><span>{k}</span><input type="number" min="0" value={v} onChange={e=>setBudget({...budget,[k]:Number(e.target.value)})}/></label>)}<button className="primary wide" onClick={()=>setBudget(BASE_BUDGET)}>Reset baseline</button></section><section className="card packing"><span className="eyebrow">PACKING CONTROL</span><h3>Departure checklist</h3>{packing.map(x=><label className="pack" key={x}><input type="checkbox" checked={packed.includes(x)} onChange={()=>setPacked(packed.includes(x)?packed.filter(y=>y!==x):[...packed,x])}/><span>{x}</span></label>)}<button className="cardButton" onClick={()=>{const x=prompt('Add packing item');if(x?.trim())setPacking([...packing,x.trim()])}}>+ Add item</button></section></div>}
  </div>
  <section className="sourceStrip"><div><span className="eyebrow">PLANNING SOURCES</span><b>Route structure uses official Brittany tourism itinerary concepts; tide integration is designed for official SHOM data.</b></div><div className="sourceLinks"><a href="https://www.tourismebretagne.com/destinations/itineraires/" target="_blank">Tourisme Bretagne ↗</a><a href="https://diffusion.shom.fr/portail-horaires-des-marees.html" target="_blank">Official SHOM tides ↗</a></div></section>
  <footer><span>BRITTANY / TRIP SYSTEM v2.0</span><span>Local-first · exportable · API-ready</span><button onClick={()=>window.print()}>Print / PDF</button><span>© 2026</span></footer>{toast&&<div className="toast">{toast}</div>}
 </main>
}

function RouteMap({day,setDay,full=false}){const pts=[['Rennes',80,240],['Mont',155,165],['St-Malo',205,112],['Dinan',270,135],['Pink',350,220],['Crozon',410,170],['Raz',505,112],['Quimper',535,150],['Carnac',585,205],['Vannes',650,135]];return <div className={full?'mapCard fullMap':'mapCard'}><div className="mapNoise"/><div className="mapTitle"><span>{full?'INTERACTIVE ROUTE':'ROUTE / LIVE'}</span><b>{full?'Brittany master route':`Selected: Day ${day}`}</b></div><svg viewBox="0 0 760 330" className="routeSvg"> <path d="M80 240 C140 185 150 90 235 115 S350 260 410 170 S520 80 650 135" className="coast"/><path d="M80 240 C155 190 165 105 245 122 S350 245 410 170 S520 95 650 135" className="route"/>{pts.map(([n,x,y],i)=><g key={n} onClick={()=>setDay(i+1)} className="mapPoint"><circle cx={x} cy={y} r={day===i+1?9:5} className={day===i+1?'dot selected':'dot'}/><text x={x+10} y={y-10}>{n}</text></g>)}</svg><div className="mapFooter"><span>↗ Scenic route</span><span>◉ Tide-aware</span><span>⌁ Click a stop</span></div></div>}
